
import { Montserrat } from "next/font/google";
import "./globals.scss";
import NextTopLoader from "nextjs-toploader";
import { Suspense } from "react";
import { App as AntdApp, ConfigProvider, theme } from "antd";
import viVN from "antd/locale/vi_VN";
import dayjs from "dayjs";
import "dayjs/locale/vi";

dayjs.locale("vi");

const montserrat = Montserrat({
  subsets: ["latin", "vietnamese"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-montserrat",
  display: "swap",
});

export const metadata = {
  title: "SWD Project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="vi" className={montserrat.variable}>
      <body>
        <NextTopLoader color="#1677ff" height={3} showSpinner={false} />
        <ConfigProvider
          locale={viVN}
          theme={{
            algorithm: theme.defaultAlgorithm,
            token: {
              colorPrimary: "#1677ff",
              borderRadius: 8,
              fontFamily: "var(--font-montserrat)",
            },
          }}
        >
          {/* Ant Design App Provider — cần cho notification, message, modal */}
          <AntdApp>
            <main>
              <Suspense fallback={<div>Loading...</div>}>{children}</Suspense>
            </main>
          </AntdApp>
        </ConfigProvider>
      </body>
    </html>
  );
}
