'use client'
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.scss";
import NextTopLoader from "nextjs-toploader";
import { Suspense } from "react";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import Header2 from "@/components/layout/Header2";
import Footer2 from "@/components/layout/Footer2";
import { usePathname } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Ê Pay",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname();

  // Kiểm tra path có phải /login hoặc /register
  const isAuthPage = ["/login", "/register"].includes(pathname);

  return (
    <>
      <NextTopLoader />
      {isAuthPage ? <Header2 /> : <Header />}
      <main>
        <Suspense fallback={<div>Loading...</div>}>{children}</Suspense>
      </main>
      {isAuthPage ? <Footer2 /> : <Footer />}
    </>
  );
}
